---
- name: Reload systemd
  become: true
  become_method: sudo
  command: systemctl daemon-reload

- name: Restart rabbitmq
  become: true
  become_method: sudo
  service:
    name: rabbitmq-server
    state: restarted

- name: Restart sensu-api
  become: true
  become_method: sudo
  service:
    name: sensu-api
    state: restarted
...
